name: Bench

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  bench:
    name: Bench frameworks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'yarn'

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: bench-yarn-cache

      - name: 'Install dependencies'
        run: yarn install --immutable --mode=skip-build

      - name: 'Build app'
        run: |
          yarn remix build
          yarn next build

      - name: 'Run benchmark'
        run: node --expose-gc --experimental-fetch cold-boot.mjs
        env:
          NODE_ENV: 'production'
